services:
  whoknows_variations_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: whoknows_variations_dev
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app/src # your code lives here (hot reload)
      - go-mod-cache:/go/pkg # Go modules
      - dev-data:/usr/src/app/data # database
      - dev-cache:/usr/src/app/.cache # Go build cache
    working_dir: /usr/src/app/src
    environment:
      - GIN_MODE=debug
      - DATABASE_URL=postgres://whoknows:supersecret@postgres:5432/whoknows?sslmode=disable
    restart: unless-stopped
    networks:
      - appnet
    depends_on:
      - prometheus
      - grafana
      - postgres
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.dev.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - appnet

  grafana:
    image: grafana/grafana:10.2.4
    ports:
      - "3000:3000"
    networks:
      - appnet

  nginx_dev:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf-dev:/etc/nginx/conf.d:ro
      - ./public:/usr/src/app/src/public:ro
    depends_on:
      - whoknows_variations_dev
    networks:
      - appnet
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: whoknows_deployment_postgres_1
    environment:
      POSTGRES_USER: whoknows
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: whoknows
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - appnet

  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: go test -v ./...

volumes:
  go-mod-cache:
  dev-data:
  dev-cache:
  postgres_data:

networks:
  appnet:
    driver: bridge
