services:
  whoknows_variations:
    image: bikstok/whoknows_variations:latest
    expose:
      - "8080"
    restart: unless-stopped
    environment:
      - GIN_MODE=release
      - DATABASE_URL=postgres://whoknows:supersecret@postgres:5432/whoknows?sslmode=disable
    volumes:
      - appdata:/usr/src/app/data
    depends_on:
      - postgres
    networks:
      - appnet

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf-prod:/etc/nginx/conf.d:ro
      - /etc/letsencrypt/live/femprocentoppetid.dk:/etc/letsencrypt/live/femprocentoppetid.dk
      - /etc/letsencrypt/archive/femprocentoppetid.dk:/etc/letsencrypt/archive/femprocentoppetid.dk
    depends_on:
      - whoknows_variations
    restart: unless-stopped
    networks:
      - appnet

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: whoknows
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: whoknows
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - appnet

volumes:
  appdata:
  postgres_data:

networks:
  appnet:
    driver: bridge
